"""Generate Mermaid diagrams of the link graph, rendered natively by Obsidian.

  <folder>/_diagrams.md  local: linked files in this folder + their links
  .quack/diagram.md      whole-graph: every linked file, clustered by folder

The per-folder file is `_diagrams.md` (no leading dot) so Obsidian renders
the Mermaid in-app; it is excluded from file discovery so doctor/indexer
never treat it as content. Only files that participate in the link graph are
drawn, so a code repo of unlinked files does not produce a wall of nodes.

Like the indexes, these are fully derived from files + wikilinks and
regenerated each run, never hand-edited.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Callable, TYPE_CHECKING

from .core import Space

if TYPE_CHECKING:
    from .core import IgnoreRuleset

GENERATED_HEADER = (
    "# GENERATED by `quack diagram`, do not edit by hand.\n\n"
)


def _node_id(name: str) -> str:
    """Mermaid-safe node id."""
    return "n_" + "".join(c if c.isalnum() else "_" for c in name)


def _linked_targets(space: Space) -> set[str]:
    """Names that some file links to (so target-only files still get a node)."""
    targets: set[str] = set()
    for e in space.entries:
        targets.update(e.links)
    return targets


def _mermaid_for(notes, all_names: set[str], title: str) -> str:
    """Build a flowchart from a set of notes. Edges to notes outside the set
    are drawn as dangling targets; broken links get a distinct style."""
    lines = ["```mermaid", "flowchart LR"]
    local = {n.name for n in notes}
    rendered: set[str] = set()

    for n in notes:
        lines.append(f'    {_node_id(n.name)}["{n.name}"]')
        rendered.add(n.name)

    for n in notes:
        for target in n.links:
            if target not in rendered:
                label = target if target in all_names else f"{target} ⚠"
                lines.append(f'    {_node_id(target)}["{label}"]')
                rendered.add(target)
            lines.append(f"    {_node_id(n.name)} --> {_node_id(target)}")

    # Style external + broken targets differently from local notes.
    for name in rendered:
        if name in local:
            continue
        cls = "broken" if name not in all_names else "external"
        lines.append(f"    class {_node_id(name)} {cls}")
    lines.append("    classDef external fill:#eee,stroke:#999,color:#333;")
    lines.append("    classDef broken fill:#fdd,stroke:#c00,color:#900;")
    lines.append("```")
    return GENERATED_HEADER + f"## {title}\n\n" + "\n".join(lines) + "\n"


def _folder_ignored(folder_rel: str, ignores: "IgnoreRuleset") -> bool:
    """True when *folder_rel* or any ancestor directory is ignored."""
    parts = folder_rel.split("/")
    for i in range(len(parts)):
        rel = "/".join(parts[: i + 1])
        if ignores.is_ignored(parts[i], rel):
            return True
    return False


def write_folder_diagrams(
    space: Space, ignores: "IgnoreRuleset | None" = None
) -> list[Path]:
    all_names = set(space.by_name)
    ignore_set = ignores or set()
    grouped: dict[str, list] = defaultdict(list)
    for e in space.entries:
        if e.links:  # only files that participate in the link graph
            grouped[e.folder].append(e)

    written: list[Path] = []
    for folder_rel, entries in grouped.items():
        if not folder_rel:  # skip root-level loose files; covered by global
            continue
        if ignore_set and _folder_ignored(folder_rel, ignore_set):
            continue
        folder = space.root / folder_rel
        out = folder / "_diagrams.md"
        out.write_text(_mermaid_for(entries, all_names, f"{folder_rel} link graph"))
        written.append(out)
    return written


def _entry_depth(folder: str) -> int:
    """Depth of a file: 0 for root-level, 1 for one level in, etc."""
    return 0 if not folder else folder.count("/") + 1


def write_global_diagram(
    space: Space,
    max_depth: int = 3,
    ignores: "IgnoreRuleset | None" = None,
) -> Path:
    """One whole-graph diagram of the linked files, grouped into folder
    subgraphs. Only files at folder depth ≤ *max_depth* are included, so
    large spaces produce a top-level structural overview rather than an
    unrenderable wall of nodes. Ignored directories are excluded."""
    ignore_set = ignores or set()
    all_names = set(space.by_name)
    # Bind once: referencing _linked_targets() inside the comprehension is O(n²).
    targets = _linked_targets(space)
    linked = [
        e for e in space.entries
        if (e.links or e.name in targets)
        and _entry_depth(e.folder) <= max_depth
        and not (ignore_set and e.folder and _folder_ignored(e.folder, ignore_set))
    ]

    out = space.root / ".quack" / "diagram.md"

    if not linked:
        out.write_text(
            GENERATED_HEADER
            + "## Vault link graph\n\n"
            + f"_No linked files found at depth ≤ {max_depth}. "
            + "Raise `index.diagram_max_depth` in `.quack/config.yaml` to include deeper folders._\n"
        )
        return out

    by_folder: dict[str, list] = defaultdict(list)
    for e in linked:
        by_folder[e.folder or "(root)"].append(e)

    lines = ["```mermaid", "flowchart LR"]
    for folder, entries in sorted(by_folder.items()):
        sub = "".join(c if c.isalnum() else "_" for c in folder)
        lines.append(f'    subgraph {sub}["{folder}"]')
        for e in entries:
            lines.append(f'        {_node_id(e.name)}["{e.name}"]')
        lines.append("    end")
    seen_external: set[str] = set()
    for e in linked:
        for target in e.links:
            if target not in all_names and target not in seen_external:
                lines.append(f'    {_node_id(target)}["{target} ⚠"]:::broken')
                seen_external.add(target)
            lines.append(f"    {_node_id(e.name)} --> {_node_id(target)}")
    lines.append("    classDef broken fill:#fdd,stroke:#c00,color:#900;")
    lines.append("```")

    out.write_text(GENERATED_HEADER + "## Vault link graph\n\n" + "\n".join(lines) + "\n")
    return out


def diagram(
    explicit_root: str | None = None,
    progress: Callable[[int, int, str], None] | None = None,
) -> dict:
    from .config import Config
    from .core import load_ignores, find_root

    root = find_root(explicit_root)
    config = Config.load(str(root))
    ignores = load_ignores(root)
    max_depth = config.index.diagram_max_depth

    space = Space.load(explicit_root, progress=progress)

    # Count nodes that will appear in the global diagram (depth-filtered, non-ignored).
    ignore_set = ignores or set()
    targets = _linked_targets(space)
    global_nodes = sum(
        1 for e in space.entries
        if (e.links or e.name in targets)
        and _entry_depth(e.folder) <= max_depth
        and not (ignore_set and e.folder and _folder_ignored(e.folder, ignore_set))
    )
    total_linked = sum(1 for e in space.entries if e.links or e.name in targets)
    total = max(len(space.entries), 1)

    if progress is not None:
        progress(0, total, f"Writing folder diagrams")
    folders = write_folder_diagrams(space, ignores=ignores)

    if progress is not None:
        progress(total, total,
            f"Writing global diagram — {global_nodes:,} nodes at depth ≤ {max_depth}"
            + (f" ({total_linked - global_nodes:,} deeper nodes excluded)" if total_linked > global_nodes else "")
        )
    global_path = write_global_diagram(space, max_depth=max_depth, ignores=ignores)

    return {
        "folder_diagrams": len(folders),
        "global": str(global_path),
        "global_nodes": global_nodes,
        "total_linked": total_linked,
        "max_depth": max_depth,
    }
