"""Generate Mermaid diagrams of the link graph, rendered natively by Obsidian.

  <folder>/_diagrams.md  local: linked files in this folder + their links
  .quack/diagram.md      whole-graph: every linked file, clustered by folder

The per-folder file is `_diagrams.md` (no leading dot) so Obsidian renders
the Mermaid in-app; it is excluded from file discovery so doctor/indexer
never treat it as content. Only files that participate in the link graph are
drawn, so a code repo of unlinked files does not produce a wall of nodes.

Like the indexes, these are fully derived from files + wikilinks and
regenerated each run, never hand-edited.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from .core import Space

GENERATED_HEADER = (
    "# GENERATED by `quack diagram`, do not edit by hand.\n\n"
)


def _node_id(name: str) -> str:
    """Mermaid-safe node id."""
    return "n_" + "".join(c if c.isalnum() else "_" for c in name)


def _linked_targets(space: Space) -> set[str]:
    """Names that some file links to (so target-only files still get a node)."""
    targets: set[str] = set()
    for e in space.entries:
        targets.update(e.links)
    return targets


def _mermaid_for(notes, all_names: set[str], title: str) -> str:
    """Build a flowchart from a set of notes. Edges to notes outside the set
    are drawn as dangling targets; broken links get a distinct style."""
    lines = ["```mermaid", "flowchart LR"]
    local = {n.name for n in notes}
    rendered: set[str] = set()

    for n in notes:
        lines.append(f'    {_node_id(n.name)}["{n.name}"]')
        rendered.add(n.name)

    for n in notes:
        for target in n.links:
            if target not in rendered:
                label = target if target in all_names else f"{target} ⚠"
                lines.append(f'    {_node_id(target)}["{label}"]')
                rendered.add(target)
            lines.append(f"    {_node_id(n.name)} --> {_node_id(target)}")

    # Style external + broken targets differently from local notes.
    for name in rendered:
        if name in local:
            continue
        cls = "broken" if name not in all_names else "external"
        lines.append(f"    class {_node_id(name)} {cls}")
    lines.append("    classDef external fill:#eee,stroke:#999,color:#333;")
    lines.append("    classDef broken fill:#fdd,stroke:#c00,color:#900;")
    lines.append("```")
    return GENERATED_HEADER + f"## {title}\n\n" + "\n".join(lines) + "\n"


def write_folder_diagrams(space: Space) -> list[Path]:
    all_names = set(space.by_name)
    grouped: dict[str, list] = defaultdict(list)
    for e in space.entries:
        if e.links:  # only files that participate in the link graph
            grouped[e.folder].append(e)

    written: list[Path] = []
    for folder_rel, entries in grouped.items():
        if not folder_rel:  # skip root-level loose files; covered by global
            continue
        folder = space.root / folder_rel
        out = folder / "_diagrams.md"
        out.write_text(_mermaid_for(entries, all_names, f"{folder_rel} link graph"))
        written.append(out)
    return written


def write_global_diagram(space: Space) -> Path:
    """One whole-graph diagram of the linked files, grouped into folder
    subgraphs. Files with no links are omitted to keep the graph legible."""
    all_names = set(space.by_name)
    linked = [e for e in space.entries if e.links or e.name in _linked_targets(space)]
    by_folder: dict[str, list] = defaultdict(list)
    for e in linked:
        by_folder[e.folder or "(root)"].append(e)

    lines = ["```mermaid", "flowchart LR"]
    for folder, entries in sorted(by_folder.items()):
        sub = "".join(c if c.isalnum() else "_" for c in folder)
        lines.append(f'    subgraph {sub}["{folder}"]')
        for e in entries:
            lines.append(f'        {_node_id(e.name)}["{e.name}"]')
        lines.append("    end")
    seen_external: set[str] = set()
    for e in space.entries:
        for target in e.links:
            if target not in all_names and target not in seen_external:
                lines.append(f'    {_node_id(target)}["{target} ⚠"]:::broken')
                seen_external.add(target)
            lines.append(f"    {_node_id(e.name)} --> {_node_id(target)}")
    lines.append("    classDef broken fill:#fdd,stroke:#c00,color:#900;")
    lines.append("```")

    out = space.root / ".quack" / "diagram.md"
    out.write_text(GENERATED_HEADER + "## Vault link graph\n\n" + "\n".join(lines) + "\n")
    return out


def diagram(explicit_root: str | None = None) -> dict:
    space = Space.load(explicit_root)
    folders = write_folder_diagrams(space)
    global_path = write_global_diagram(space)
    return {
        "folder_diagrams": len(folders),
        "global": str(global_path),
    }
