"""Generate the AI-navigation layer from the space's files + links.

Derived artifacts, all regenerated from scratch each run (idempotent):

  <folder>/.index.yaml   file-level (editable): every file + description/tags
  .quack/map.yaml        folder-level: the tree + a description per folder
  .quack/quack.duckdb    the catalog: files, tags, links + FTS (built here too)

The drill-down an AI follows: GUIDE.md -> map.yaml (which folder?) ->
folder/.index.yaml (which file?) -> the file -> `quack search`/`quack sql`
to pull just the related slice from the catalog. Read cost scales with
relevance, not space size.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import yaml

from . import index_store
from .core import Space, content_folders

GENERATED_HEADER = (
    "# GENERATED by `quack reindex`, do not edit by hand.\n"
)


def _folder_description(folder: Path) -> str:
    """A folder describes itself via an optional `.folder.md` note's
    frontmatter description, falling back to empty."""
    marker = folder / ".folder.md"
    if marker.exists():
        import frontmatter

        return str(frontmatter.load(marker).get("description", "")).strip()
    return ""


def write_folder_indexes(space: Space) -> list[Path]:
    """Write/merge one editable .index.yaml per folder that contains files.

    Authored ``description``/``tags`` are already overlaid onto each entry by
    ``Space.load``; here we write them back (preserving them) alongside freshly
    derived ``links``, dropping entries for files that no longer exist."""
    grouped: dict[Path, list] = defaultdict(list)
    for e in space.entries:
        grouped[e.path.parent].append(e)

    written: list[Path] = []
    for folder, entries in grouped.items():
        rows = [
            {
                "name": e.path.name,
                "description": e.description,
                "tags": e.tags,
                "links": e.links,
                "file_modified": e.modified,
                "described_at": e.described_at,
            }
            for e in sorted(entries, key=lambda x: x.name.lower())
        ]
        written.append(index_store.write_index(folder, rows))
    return written


def write_map(space: Space) -> Path:
    """Write the folder-level map: tree + per-folder description + counts."""
    counts: dict[str, int] = defaultdict(int)
    for e in space.entries:
        counts[e.folder] += 1

    tree: dict[str, dict] = {}
    for folder in content_folders(space.root):
        rel = folder.relative_to(space.root).as_posix()
        tree[rel] = {
            "description": _folder_description(folder) or "(no description)",
            "notes": counts.get(rel, 0),
        }

    out = space.root / ".quack" / "map.yaml"
    out.write_text(
        GENERATED_HEADER
        + yaml.safe_dump(
            {"space": space.root.name, "folders": tree},
            sort_keys=False,
            allow_unicode=True,
        )
    )
    return out


def reindex(explicit_root: str | None = None) -> dict:
    """Regenerate all derived artifacts. Returns a summary.

    The graph lives in the DuckDB catalog (links table + recursive-CTE
    traversal), not a separate graph.json: `quack search`/`quack sql` pull
    only the slice they need into context instead of loading the whole graph.
    """
    from . import catalog  # local import keeps duckdb out of the hot path

    space = Space.load(explicit_root)
    indexes = write_folder_indexes(space)
    map_path = write_map(space)
    cat = catalog.build(space)
    return {
        "space": str(space.root),
        "files": len(space.entries),
        "folder_indexes": len(indexes),
        "map": str(map_path),
        "db": cat["db"],
    }
