"""Generate the AI-navigation layer from the space's files + links.

Derived artifacts, all regenerated each run (idempotent, incremental):

  <folder>/.index.yaml   editable: this folder's direct `files:` AND direct
                         `directories:` (immediate subfolders). Written for
                         every folder, including subdir-only folders and root.
  .quack/map.yaml        global: the full nested folder tree, each folder with
                         description, diagram, counts, and type/tag rollups,
                         plus a space-level rollup.
  .quack/quack.duckdb    the catalog: files, folders, tags, links + FTS.

Folder metadata (per-folder `directories:` sections, `map.yaml`, and the
catalog `folders` table) all come from one shared resolver (`folders.py`), so
they cannot drift. Recognition defaults give well-known files/folders an
instant description, written non-sticky (blank `described_at`) so they
re-derive and never masquerade as authored.

The drill-down an AI follows: map.yaml (which folder?) -> folder/.index.yaml
(which child file or subfolder?) -> the file -> `quack search`/`quack sql` to
pull just the related slice from the catalog. Read cost scales with relevance,
not space size.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path

import yaml

from . import catalog, folders, index_store
from .folders import FolderInfo
from .core import Space

GENERATED_HEADER = (
    "# GENERATED by `quack reindex`, do not edit by hand.\n"
)


def write_folder_indexes(
    space: Space,
    folder_infos: dict[str, FolderInfo],
    dirty_folders: set[Path] | None = None,
) -> list[Path]:
    """Write/merge one editable .index.yaml per folder — including folders that
    contain only subfolders, and the root — each listing its direct ``files:``
    and direct ``directories:``.

    When *dirty_folders* is supplied only those folders are (re)written; pass
    ``None`` to write every folder (full rebuild). Truly-empty folders (no
    direct files and no subfolders) are skipped.
    """
    grouped: dict[str, list] = defaultdict(list)
    for e in space.entries:
        grouped[e.folder].append(e)
    kids_by_parent = folders.children_index(folder_infos)

    dirty_resolved = (
        {p.resolve() for p in dirty_folders} if dirty_folders is not None else None
    )

    written: list[Path] = []
    for rel, info in folder_infos.items():
        folder = space.root if info.is_root else space.root / rel
        if dirty_resolved is not None and folder.resolve() not in dirty_resolved:
            continue
        file_rows = [
            {
                "name": e.path.name,
                "description": e.description,
                "tags": e.tags,
                "links": e.links,
                "file_modified": e.modified,
                "described_at": e.described_at,
            }
            for e in sorted(grouped.get(rel, []), key=lambda x: x.name.lower())
        ]
        dir_rows = [
            {
                "name": c.name,
                "description": c.description,
                "tags": c.tags,
                "n_files": c.n_files,
                "diagram": c.diagram,
                "types": c.types,
                "described_at": c.described_at,
            }
            for c in kids_by_parent.get(rel, [])
        ]
        if not file_rows and not dir_rows:
            # Folder has nothing to describe. Remove any index left over from
            # when it did, so it can't list now-deleted children forever.
            stale = index_store.index_path(folder)
            if stale.exists():
                stale.unlink()
            continue
        written.append(index_store.write_index(folder, file_rows, dir_rows))
    return written


def write_map(space: Space, folder_infos: dict[str, FolderInfo]) -> Path:
    """Write the global folder-level map: the full nested tree, each folder
    enriched with description, diagram, counts, and type/tag rollups, plus a
    space-level rollup. Derived from the shared folder resolver."""
    tree: dict[str, dict] = {}
    for rel in sorted(r for r in folder_infos if r != ""):
        info = folder_infos[rel]
        entry: dict = {
            "description": info.description or "(no description)",
            "files": info.n_files,
        }
        if info.diagram:
            entry["diagram"] = info.diagram
        if info.types:
            entry["types"] = info.types
        if info.tag_rollup:
            entry["tags"] = info.tag_rollup
        tree[rel] = entry

    space_types: Counter = Counter()
    space_tags: Counter = Counter()
    for e in space.entries:
        space_types[e.ext or "other"] += 1
        space_tags.update(e.tags)

    out = space.root / ".quack" / "map.yaml"
    out.write_text(
        GENERATED_HEADER
        + yaml.safe_dump(
            {
                "space": space.root.name,
                "files": len(space.entries),
                "types": dict(space_types),
                "tags": [t for t, _ in space_tags.most_common(10)],
                "folders": tree,
            },
            sort_keys=False,
            allow_unicode=True,
        )
    )
    return out


def _expand_dirty(dirty: set[Path], root: Path) -> set[Path]:
    """Add every ancestor folder (up to and including root) of each dirty
    folder, since a child's counts/rollups change its parents' ``directories:``
    sections."""
    root = root.resolve()
    out: set[Path] = set()
    for p in dirty:
        cur = p.resolve()
        while True:
            out.add(cur)
            if cur == root or root not in cur.parents:
                break
            cur = cur.parent
    out.add(root)
    return out


def _folder_path(root: Path, rel: str) -> Path:
    """Filesystem path of a folder rel ("" → root)."""
    return root if rel == "" else root / rel


def _parent_folder_path(root: Path, rel: str) -> Path:
    """Filesystem path of the folder whose index *describes* folder *rel* —
    i.e. its parent ("" → root)."""
    parent_rel = rel.rsplit("/", 1)[0] if "/" in rel else ""
    return _folder_path(root, parent_rel)


def _dirty_folders(
    space: Space, folder_infos: dict[str, FolderInfo]
) -> set[Path] | None:
    """Return folders that need their index refreshed, or None for a full build.

    None means: no usable catalog exists yet, rebuild everything.
    An empty set means: nothing changed, safe to skip.
    A non-empty set: only these folders (and the catalog) need updating.

    Compares each file's current mtime, description, tags, and described_at —
    and each folder's resolved description/described_at — directly against what
    is stored in the catalog. No timestamp arithmetic, no sub-second races.

    Deleted files/folders are detected by set-diffing indexed vs current; the
    folder (or parent) that used to contain them is marked dirty.
    """
    db = catalog.db_path(space)
    if not db.exists():
        return None

    try:
        con = catalog.connect_path(db)
        try:
            rows = con.execute(
                "SELECT rel, file_modified, description, tags_csv, described_at FROM files"
            ).fetchall()
            folder_rows = con.execute(
                "SELECT folder, description, n_files, diagram, described_at FROM folders"
            ).fetchall()
        finally:
            con.close()
    except Exception:
        # Any error (corrupt DB, schema mismatch, I/O) → full rebuild is safe.
        return None

    # Build a lookup keyed by rel for O(1) comparisons.
    indexed: dict[str, tuple[str, str, str, str]] = {
        rel: (file_mod or "", desc or "", tags_csv or "", desc_at or "")
        for rel, file_mod, desc, tags_csv, desc_at in rows
    }
    indexed_rels = set(indexed)
    current_rels = {e.rel for e in space.entries}
    root = space.root
    dirty: set[Path] = set()

    for e in space.entries:
        if e.rel not in indexed:
            dirty.add(e.path.parent)  # new file
            continue
        stored_mtime, stored_desc, stored_tags_csv, stored_desc_at = indexed[e.rel]
        if e.modified != stored_mtime:
            dirty.add(e.path.parent)
        elif e.description != stored_desc:
            dirty.add(e.path.parent)
        elif ",".join(e.tags) != stored_tags_csv:
            dirty.add(e.path.parent)
        elif e.described_at != stored_desc_at:
            dirty.add(e.path.parent)

    # Deleted files — mark the folder they used to live in.
    for rel in indexed_rels - current_rels:
        folder_part = rel.rsplit("/", 1)[0] if "/" in rel else "."
        dirty.add((root / folder_part).resolve() if folder_part != "." else root.resolve())

    # Folder metadata drift (authored/vanished description, changed counts, a
    # newly generated diagram). The folder is described in its *parent's*
    # index, so mark the parent dirty.
    stored_folders = {
        f: (d or "", int(n or 0), dg or "", da or "")
        for f, d, n, dg, da in folder_rows
    }
    current_folders = {
        i.rel: (i.description, i.n_files, i.diagram, i.described_at)
        for i in folder_infos.values()
        if not i.is_root
    }
    for rel, cur in current_folders.items():
        if stored_folders.get(rel) != cur:
            dirty.add(_parent_folder_path(root, rel))
    for rel in set(stored_folders) - set(current_folders):  # vanished folder
        dirty.add(_parent_folder_path(root, rel))

    return dirty


def reindex(explicit_root: str | None = None) -> dict:
    """Regenerate all derived artifacts. Returns a summary.

    Skips unchanged folders: only .index.yaml files for folders whose content
    or metadata changed are rewritten.  When nothing has changed since the last
    run the catalog and map are also skipped and the call returns immediately.

    The graph lives in the DuckDB catalog (links table + recursive-CTE
    traversal), not a separate graph.json: `quack search`/`quack sql` pull
    only the slice they need into context instead of loading the whole graph.
    """
    from .gitignore import ensure_gitignore

    space = Space.load(explicit_root)
    ensure_gitignore(space.root)

    # Resolve folder metadata once and feed it to every consumer (dirty
    # detection, indexes, map, catalog) so they can't drift.
    folder_infos = folders.resolve_folders(space)
    dirty = _dirty_folders(space, folder_infos)

    if dirty is not None and not dirty:
        # Nothing changed — return without touching any files.
        return {
            "space": str(space.root),
            "files": len(space.entries),
            "folder_indexes": 0,
            "map": str(space.root / ".quack" / "map.yaml"),
            "db": str(catalog.db_path(space)),
        }

    # dirty is None (first run / unusable catalog) or a non-empty set. When
    # only some folders are dirty, also refresh their ancestors, whose
    # directory rollups changed.
    if dirty is not None:
        dirty = _expand_dirty(dirty, space.root)
    indexes = write_folder_indexes(space, folder_infos, dirty_folders=dirty)
    map_path = write_map(space, folder_infos)
    cat = catalog.build(space, folder_infos)
    return {
        "space": str(space.root),
        "files": len(space.entries),
        "folder_indexes": len(indexes),
        "map": str(map_path),
        "db": cat["db"],
    }
